### ISSUE TITLE
"Reset" button covers the legend in Project Timelines

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#15]
The chart Project Timelines can be zoomed and panned. After zooming/panning a "Reset" button appears allowing the user to reset the chart in its initial state.
The button appears at the top and covers the legend. It should be repositioned in such a way that works for all screen sizes.

**Comment by jbenndorf** [comment]
This issue fix repositioned the reset button to the left hand corner of the chart. Ideally the button would fade away/dissapear when pressed, until zooming/panning actions are performed again. This is the subject of the next fix.

**Comment by jbenndorf** [comment]
Refactoring of the new toggleResetButton() method will subject to the next fix.
