### ISSUE TITLE
Resize the charts on window.resize

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#17]
When the browser window is resized, for example the orientation of a mobile device is changed, the chart keeps its initial size. It would be much better to make it responsible and re-render the whole chart to reflect the size of the window.

**Comment by jbenndorf** [comment]
The previous fix allowed for responsive resizing of the chart when the browser window resizes.
However, the project lengths and the ActiveProject toggler do not adjust accordingly, which will be subject to the next fix.

**Comment by cezar77** [comment]
Here are some good reads on this issue:

https://www.d3-graph-gallery.com/graph/custom_responsive.html
https://benclinkinbeard.com/d3tips/make-any-chart-responsive-with-one-function/
https://chartio.com/resources/tutorials/how-to-resize-an-svg-when-the-window-is-resized-in-d3-js/

These questions on StackOverflow are about this topic too:

https://stackoverflow.com/questions/16265123/resize-svg-when-window-is-resized-in-d3-js
https://stackoverflow.com/questions/46951478/d3js-svg-element-not-getting-resized-on-changing-window-size
https://stackoverflow.com/questions/25555257/redrawing-svg-on-resize

And some code examples on bl.ocks:

https://bl.ocks.org/curran/3a68b0c81991e2e94b19
https://bl.ocks.org/rudedogg187/8c86bae1f1eb0ac4008c5f7ff5f172a6

**Comment by cezar77** [comment]
Another good read on resizing SVGs:

https://css-tricks.com/scale-svg/
