### ISSUE TITLE
Refactor the syntax of props in the Vue code

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#18]
The **props** in the Vue code are written like:

    props: ['margin']

This should be refactored to comply with the Vue style guide, for example:

    props: {
        margin: {
            type: Number,
            required: true
        }
    }

All occurences should be refactored.

**Comment by cezar77** [comment]
This seems to be resolved. Can we close it?

**Comment by jbenndorf** [comment]
Yes I've doubled checked and I think we can close it, too.
