### ISSUE TITLE
Refactoring of the VueJS frontend application

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#38]
The VueJS frontend application should be refactored. There are many things that do not follow best practices and there's a lot of room to improve the code and make it more maintenable. 

<hr>
The templates of the views have repeating parts about the loading and error notifications. It would be best to create separate components for them.
Maybe we could create something like `NotificationContainer` and components for `ErrorNotification` and `LoadingNotification`.
We could use the library `NProgress`.

<hr>
How about modularisation of the store? We could split the logic and create separate modules for projects and world countries. We could create directory `modules` under `store` and place all modules there.
Should we replace the async functions with proper Promises?
Should we rename the mutations to folow best naming practices and be all capital letters?

Would it be better to create a separate service for the API requests?

The mutation `sortAndGroupProjects` doesn't look very clean. Should we split it, create a getter or do something else?

<hr>
When we use `mapState` (or `mapActions`) should we use verbose or shorthand writing? Like:

    mapState({
        some_mutation: (state) => state.some_mutation
    })

or

    mapState([
        'some_mutation'
    ])

<hr>
We could use `mapActions` instead of calling `this.$store.dispatch` in `App.vue`.

<hr>
Resizing of SVG graphics should be done in a mixin or a separate component, whatever fits better.

<hr>
The components `XAxis` and `YAxis` take a lot of props. Should the props rather be grouped in objects? The props that contain information about dimensions and positioning of the SVG chart could be put together in one object.

**Comment by jbenndorf** [comment]
Hi Cezar, I think all of these enhancements would be great additions to the frontend application. 

I am just slightly unsure about replacing the async functions with proper Promises, what benefits do you think this would have?

**Comment by cezar77** [comment]
The async functions are "[syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar)". In the background they are converted to Promise objects.

Your point on the benefits is justified. We have to evaluate the costs and benefits of the refactoring.

**Comment by jbenndorf** [comment]
Perhaps we could focus on the other enhancements first and then have another look at the async functions?

I was wondering how you would like be to start tackling the enhancements (e.g. the modularisation of the store, which I think would be a very effective enhancement), should I open these up as a new issue?

**Comment by cezar77** [comment]
This issue has been resolved.
