### ISSUE TITLE
Modularisation of the Vuex store

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#40]
Here we can discuss all steps necessary for modularisation of the Vuex store.

This issue is continuation of the the issue #38.

**Comment by cezar77** [comment]
The branch modularisation contains the relevant changes.

The Vuex store now has two modules:
- auth: code for authentication with JWT to the REST API
- project: code for fetching the projects from the endpoint /api/projects

Two more modules should be created:
- error: code for managing the errors
- loading: code for managing the loading status

The code for fetching the border shapes of the countries is discarded completely. The topojson file is now placed inside the Vue application and is imported in a single line inside `WorldMap.vue`:

    import worldCountries from '../data/world-countries.json';

**Comment by cezar77** [comment]
Instead of creating a module for loading, we could try using the library NProgress:
https://ricostacruz.com/nprogress/

**Comment by jbenndorf** [comment]
Would the NProgress library replace all currently implemented loading functionality?

**Comment by cezar77** [comment]
> Would the NProgress library replace all currently implemented loading functionality?

I have already implemented NProgress and discarded the old code regulating the loading features. Further enhancements are possible, in particular adding some CSS to create better visual experience.

**Comment by cezar77** [comment]
This issue has been resolved.
