### ISSUE TITLE
Add ManyToMany relation between Project and AnimalSpecies

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#6]
A project is working on a primary animal species (it can be more than one). We have to create a *ManyToMany* relation between the entities `Project` and `AnimalSpecies`.

In the `ProjectAdmin` we have to add a widget for choosing `AnimalSpecies`.

**Comment by Mirieri** [comment]
We should maintain the use of multiple use statement since Symfony auto generating code throws an error on single use statements. This is to avoid unnecessary errors in the future.
